/*******************************************************************************
* File Name: I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN.h
* Version 2.80
*
*  Description:
*     Contains the function prototypes and constants available to the timer
*     user module.
*
*   Note:
*     None
*
********************************************************************************
* Copyright 2008-2017, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CY_TIMER_I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_H)
#define CY_TIMER_I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_H

#include "cytypes.h"
#include "cyfitter.h"
#include "CyLib.h" /* For CyEnterCriticalSection() and CyExitCriticalSection() functions */

extern uint8 I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_initVar;

/* Check to see if required defines such as CY_PSOC5LP are available */
/* They are defined starting with cy_boot v3.0 */
#if !defined (CY_PSOC5LP)
    #error Component Timer_v2_80 requires cy_boot v3.0 or later
#endif /* (CY_ PSOC5LP) */


/**************************************
*           Parameter Defaults
**************************************/

#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Resolution                 8u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction         0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter      0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareCaptureMode        0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareTriggerMode        0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWEnable              1u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_EnableTriggerMode          0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_InterruptOnCaptureCount    0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RunModeUsed                0u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ControlRegRemoved          1u

#if defined(I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED            (0u)
#elif  (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED            (0u)
#else 
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED            (1u)
#endif /* End I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG */


/***************************************
*       Type defines
***************************************/


/**************************************************************************
 * Sleep Wakeup Backup structure for Timer Component
 *************************************************************************/
typedef struct
{
    uint8 TimerEnableState;
    #if(!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction)

        uint8 TimerUdb;
        uint8 InterruptMaskValue;
        #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter)
            uint8 TimerCaptureCounter;
        #endif /* variable declarations for backing up non retention registers in CY_UDB_V1 */

        #if (!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED)
            uint8 TimerControlRegister;
        #endif /* variable declaration for backing up enable state of the Timer */
    #endif /* define backup variables only for UDB implementation. Fixed function registers are all retention */

}I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_backupStruct;


/***************************************
*       Function Prototypes
***************************************/

void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Start(void) ;
void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Stop(void) ;

void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SetInterruptMode(uint8 interruptMode) ;
uint8   I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadStatusRegister(void) ;
/* Deprecated function. Do not use this in future. Retained for backward compatibility */
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_GetInterruptSource() I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadStatusRegister()

#if(!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED)
    uint8   I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadControlRegister(void) ;
    void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_WriteControlRegister(uint8 control) ;
#endif /* (!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UDB_CONTROL_REG_REMOVED) */

uint8  I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadPeriod(void) ;
void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_WritePeriod(uint8 period) ;
uint8  I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadCounter(void) ;
void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_WriteCounter(uint8 counter) ;
uint8  I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadCapture(void) ;
void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareCapture(void) ;

#if(!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction) /* UDB Prototypes */
    #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareCaptureMode)
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SetCaptureMode(uint8 captureMode) ;
    #endif /* (!I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction) */

    #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareTriggerMode)
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SetTriggerMode(uint8 triggerMode) ;
    #endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SoftwareTriggerMode) */

    #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_EnableTriggerMode)
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_EnableTrigger(void) ;
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_DisableTrigger(void) ;
    #endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_EnableTriggerMode) */


    #if(I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_InterruptOnCaptureCount)
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SetInterruptCount(uint8 interruptCount) ;
    #endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_InterruptOnCaptureCount) */

    #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter)
        void    I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SetCaptureCount(uint8 captureCount) ;
        uint8   I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ReadCaptureCount(void) ;
    #endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter) */

    void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_ClearFIFO(void) ;
#endif /* UDB Prototypes */

/* Sleep Retention APIs */
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Init(void)          ;
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Enable(void)        ;
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SaveConfig(void)    ;
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RestoreConfig(void) ;
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Sleep(void)         ;
void I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Wakeup(void)        ;


/***************************************
*   Enumerated Types and Parameters
***************************************/

/* Enumerated Type B_Timer__CaptureModes, Used in Capture Mode */
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__CM_NONE 0
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__CM_RISINGEDGE 1
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__CM_FALLINGEDGE 2
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__CM_EITHEREDGE 3
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__CM_SOFTWARE 4



/* Enumerated Type B_Timer__TriggerModes, Used in Trigger Mode */
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__TM_NONE 0x00u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__TM_RISINGEDGE 0x04u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__TM_FALLINGEDGE 0x08u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__TM_EITHEREDGE 0x0Cu
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN__B_TIMER__TM_SOFTWARE 0x10u


/***************************************
*    Initialial Parameter Constants
***************************************/

#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_PERIOD             215u
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_CAPTURE_MODE       ((uint8)((uint8)0u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_CAP_MODE_SHIFT))
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_TRIGGER_MODE       ((uint8)((uint8)0u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_MODE_SHIFT))
#if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_INTERRUPT_MODE (((uint8)((uint8)0u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK_SHIFT)) | \
                                                  ((uint8)((uint8)0 << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK_SHIFT)))
#else
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_INTERRUPT_MODE (((uint8)((uint8)0u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK_SHIFT)) | \
                                                 ((uint8)((uint8)0 << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK_SHIFT)) | \
                                                 ((uint8)((uint8)0 << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_INT_MASK_SHIFT)))
#endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction) */
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_CAPTURE_COUNT      (2u)
#define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_INIT_INT_CAPTURE_COUNT  ((uint8)((uint8)(1u - 1u) << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_INTCNT_SHIFT))


/***************************************
*           Registers
***************************************/

#if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingFixedFunction) /* Implementation Specific Registers and Register Constants */


    /***************************************
    *    Fixed Function Registers
    ***************************************/

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS         (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__SR0 )
    /* In Fixed Function Block Status and Mask are the same register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_MASK    (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__SR0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL        (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CFG0)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL2       (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CFG1)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL2_PTR   ( (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CFG1)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1            (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__RT1)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1_PTR        ( (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__RT1)

    #if (CY_PSOC3 || CY_PSOC5LP)
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL3       (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CFG2)
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL3_PTR   ( (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CFG2)
    #endif /* (CY_PSOC3 || CY_PSOC5LP) */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_GLOBAL_ENABLE  (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PM_ACT_CFG)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_GLOBAL_STBY_ENABLE  (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PM_STBY_CFG)

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CAP0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CAP0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PER0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PER0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CNT_CMP0 )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__CNT_CMP0 )


    /***************************************
    *    Register Constants
    ***************************************/

    /* Fixed Function Block Chosen */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_BLOCK_EN_MASK                     I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PM_ACT_MSK
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_BLOCK_STBY_EN_MASK                I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerHW__PM_STBY_MSK

    /* Control Register Bit Locations */
    /* Interrupt Count - Not valid for Fixed Function Block */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_INTCNT_SHIFT                  0x00u
    /* Trigger Polarity - Not valid for Fixed Function Block */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_MODE_SHIFT               0x00u
    /* Trigger Enable - Not valid for Fixed Function Block */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_EN_SHIFT                 0x00u
    /* Capture Polarity - Not valid for Fixed Function Block */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_CAP_MODE_SHIFT                0x00u
    /* Timer Enable - As defined in Register Map, part of TMRX_CFG0 register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE_SHIFT                  0x00u

    /* Control Register Bit Masks */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE                        ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE_SHIFT))

    /* Control2 Register Bit Masks */
    /* As defined in Register Map, Part of the TMRX_CFG1 register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL2_IRQ_SEL_SHIFT                 0x00u
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL2_IRQ_SEL                      ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL2_IRQ_SEL_SHIFT))

    #if (CY_PSOC5A)
        /* Use CFG1 Mode bits to set run mode */
        /* As defined by Verilog Implementation */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT                 0x01u
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_MASK                 ((uint8)((uint8)0x07u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT))
    #endif /* (CY_PSOC5A) */
    #if (CY_PSOC3 || CY_PSOC5LP)
        /* Control3 Register Bit Locations */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_RCOD_SHIFT        0x02u
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENBL_SHIFT        0x00u
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT        0x00u

        /* Control3 Register Bit Masks */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_RCOD_MASK  ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_RCOD_SHIFT)) /* ROD and COD bit masks */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENBL_MASK  ((uint8)((uint8)0x80u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENBL_SHIFT)) /* HW_EN bit mask */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_MASK  ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT)) /* Run mode bit mask */

        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_RCOD       ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_RCOD_SHIFT))
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENBL       ((uint8)((uint8)0x80u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENBL_SHIFT))
    #endif /* (CY_PSOC3 || CY_PSOC5LP) */

    /*RT1 Synch Constants: Applicable for PSoC3 and PSoC5LP */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1_SHIFT                       0x04u
    /* Sync TC and CMP bit masks */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1_MASK                        ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNC                            ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_RT1_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNCDSI_SHIFT                   0x00u
    /* Sync all DSI inputs with Mask  */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNCDSI_MASK                    ((uint8)((uint8)0x0Fu << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNCDSI_SHIFT))
    /* Sync all DSI inputs */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNCDSI_EN                      ((uint8)((uint8)0x0Fu << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_SYNCDSI_SHIFT))

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_PULSEWIDTH            ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_PERIOD                ((uint8)((uint8)0x02u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_CONTINUOUS            ((uint8)((uint8)0x00u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_MODE_SHIFT))

    /* Status Register Bit Locations */
    /* As defined in Register Map, part of TMRX_SR0 register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT                 0x07u
    /* As defined in Register Map, part of TMRX_SR0 register, Shared with Compare Status */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT            0x06u
    /* As defined in Register Map, part of TMRX_SR0 register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK_SHIFT        (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT - 0x04u)
    /* As defined in Register Map, part of TMRX_SR0 register, Shared with Compare Status */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK_SHIFT   (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT - 0x04u)

    /* Status Register Bit Masks */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC                       ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE                  ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT))
    /* Interrupt Enable Bit-Mask for interrupt on TC */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK              ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK_SHIFT))
    /* Interrupt Enable Bit-Mask for interrupt on Capture */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK         ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK_SHIFT))

#else   /* UDB Registers and Register Constants */


    /***************************************
    *           UDB Registers
    ***************************************/

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS              (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_rstSts_stsreg__STATUS_REG )
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_MASK         (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_rstSts_stsreg__MASK_REG)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_AUX_CTRL     (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_rstSts_stsreg__STATUS_AUX_CTL_REG)
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CONTROL             (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG )
    
    #if(I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Resolution <= 8u) /* 8-bit Timer */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
    #elif(I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Resolution <= 16u) /* 8-bit Timer */
        #if(CY_PSOC3) /* 8-bit addres space */
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
        #else /* 16-bit address space */
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_A0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg16 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__16BIT_A0_REG )
        #endif /* CY_PSOC3 */
    #elif(I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_Resolution <= 24u)/* 24-bit Timer */
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
    #else /* 32-bit Timer */
        #if(CY_PSOC3 || CY_PSOC5) /* 8-bit address space */
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
        #else /* 32-bit address space */
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_F0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB          (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_PERIOD_LSB_PTR        ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_D0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB         (* (reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_A0_REG )
            #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR       ((reg32 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__32BIT_A0_REG )
        #endif /* CY_PSOC3 || CY_PSOC5 */ 
    #endif

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_COUNTER_LSB_PTR_8BIT       ((reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sT8_timerdp_u0__A0_REG )
    
    #if (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter)
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAP_COUNT              (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCapCount_counter__PERIOD_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAP_COUNT_PTR          ( (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCapCount_counter__PERIOD_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_COUNT_CTRL     (*(reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCapCount_counter__CONTROL_AUX_CTL_REG )
        #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CAPTURE_COUNT_CTRL_PTR ( (reg8 *) I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_TimerUDB_sCapCount_counter__CONTROL_AUX_CTL_REG )
    #endif /* (I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_UsingHWCaptureCounter) */


    /***************************************
    *       Register Constants
    ***************************************/

    /* Control Register Bit Locations */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_INTCNT_SHIFT              0x00u       /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_MODE_SHIFT           0x02u       /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_EN_SHIFT             0x04u       /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_CAP_MODE_SHIFT            0x05u       /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE_SHIFT              0x07u       /* As defined by Verilog Implementation */

    /* Control Register Bit Masks */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_INTCNT_MASK               ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_INTCNT_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_MODE_MASK            ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_MODE_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_EN                   ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_TRIG_EN_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_CAP_MODE_MASK             ((uint8)((uint8)0x03u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_CAP_MODE_SHIFT))
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE                    ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CTRL_ENABLE_SHIFT))

    /* Bit Counter (7-bit) Control Register Bit Definitions */
    /* As defined by the Register map for the AUX Control Register */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_CNTR_ENABLE                    0x20u

    /* Status Register Bit Locations */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT                0x00u  /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT           0x01u  /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK_SHIFT       I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK_SHIFT  I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_SHIFT          0x02u  /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFONEMP_SHIFT          0x03u  /* As defined by Verilog Implementation */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_INT_MASK_SHIFT I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_SHIFT

    /* Status Register Bit Masks */
    /* Sticky TC Event Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC                      ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT))
    /* Sticky Capture Event Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE                 ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT))
    /* Interrupt Enable Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_INT_MASK             ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_TC_SHIFT))
    /* Interrupt Enable Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_INT_MASK        ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_CAPTURE_SHIFT))
    /* NOT-Sticky FIFO Full Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL                ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_SHIFT))
    /* NOT-Sticky FIFO Not Empty Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFONEMP                ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFONEMP_SHIFT))
    /* Interrupt Enable Bit-Mask */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_INT_MASK       ((uint8)((uint8)0x01u << I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_FIFOFULL_SHIFT))

    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_ACTL_INT_EN             0x10u   /* As defined for the ACTL Register */

    /* Datapath Auxillary Control Register definitions */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_AUX_CTRL_FIFO0_CLR             0x01u   /* As defined by Register map */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_AUX_CTRL_FIFO1_CLR             0x02u   /* As defined by Register map */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_AUX_CTRL_FIFO0_LVL             0x04u   /* As defined by Register map */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_AUX_CTRL_FIFO1_LVL             0x08u   /* As defined by Register map */
    #define I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_STATUS_ACTL_INT_EN_MASK        0x10u   /* As defined for the ACTL Register */

#endif /* Implementation Specific Registers and Register Constants */

#endif  /* CY_TIMER_I_REALLY_DONT_CARE_I_JUST_WANT_TO_GIVE_THIS_COMPONENT_THE_LONGEST_NAME_I_CAN_H */


/* [] END OF FILE */
