/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "PWM_1_aliases.h"
#include "PWM_2.h"
#include "PWM_2_aliases.h"
#include "PWM_3.h"
#include "PWM_3_aliases.h"
#include "PWM_4.h"
#include "PWM_4_aliases.h"
#include "Blue.h"
#include "Blue_aliases.h"
#include "Clock_2.h"
#include "PWM_6.h"
#include "PWM_6_aliases.h"
#include "PWM_5.h"
#include "PWM_5_aliases.h"
#include "PWM_Timer.h"
#include "PWM_Timer_Pulse.h"
#include "Clock_1.h"
#include "PWM_Timer_Int.h"
#include "PinSelect.h"
#include "Green.h"
#include "Green_aliases.h"
#include "Red.h"
#include "Red_aliases.h"
#include "PWM_7.h"
#include "PWM_7_aliases.h"
#include "PWM_8.h"
#include "PWM_8_aliases.h"
#include "ADC.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "timer_clock.h"
#include "ANALOG_INT.h"
#include "Analog_Timer.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "WDT_ISR.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

